#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jun 18 17:45:35 WEST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_tb_time_impl -key {Post-Implementation:sim_1:Timing:top_tb} -tclbatch top_tb.tcl -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_time_synth.wcfg -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_time_impl.wcfg -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_behav.wcfg -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_behav1.wcfg -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_time_impl1.wcfg -log simulate.log"
xsim top_tb_time_impl -key {Post-Implementation:sim_1:Timing:top_tb} -tclbatch top_tb.tcl -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_time_synth.wcfg -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_time_impl.wcfg -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_behav.wcfg -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_behav1.wcfg -view /home/user/Documents/Embedded/8051-Pipeline/8051_S_Pipeline/top_tb_time_impl1.wcfg -log simulate.log

