set_property IOSTANDARD LVCMOS33 [get_ports {P0_gpio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0_gpio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0_gpio[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0_gpio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0_gpio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0_gpio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0_gpio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0_gpio[0]}]

set_property PACKAGE_PIN N15 [get_ports {P0_gpio[0]}]
set_property PACKAGE_PIN L14 [get_ports {P0_gpio[1]}]
set_property PACKAGE_PIN K16 [get_ports {P0_gpio[2]}]
set_property PACKAGE_PIN K14 [get_ports {P0_gpio[3]}]
set_property PACKAGE_PIN N16 [get_ports {P0_gpio[4]}]
set_property PACKAGE_PIN L15 [get_ports {P0_gpio[5]}]
set_property PACKAGE_PIN J16 [get_ports {P0_gpio[6]}]
set_property PACKAGE_PIN J14 [get_ports {P0_gpio[7]}]