#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jun 20 03:29:54 WEST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_tb_behav -key {Behavioral:sim_1:Functional:top_tb} -tclbatch top_tb.tcl -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_time_synth.wcfg -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_time_impl.wcfg -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_behav.wcfg -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_behav1.wcfg -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_time_impl1.wcfg -log simulate.log"
xsim top_tb_behav -key {Behavioral:sim_1:Functional:top_tb} -tclbatch top_tb.tcl -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_time_synth.wcfg -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_time_impl.wcfg -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_behav.wcfg -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_behav1.wcfg -view /home/telmo/Desktop/Vivado/8051/8051_S_Pipeline/top_tb_time_impl1.wcfg -log simulate.log

