# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.runs/synth_1/CPU8051.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.cache/wt [current_project]
set_property parent.project_path /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.2 [current_project]
set_property ip_output_repo /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/viny/Desktop/Final_micro_sempipeline/RAM.coe
add_files /home/viny/Desktop/Final_micro_sempipeline/program.coe
read_verilog -library xil_defaultlib {
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/defines.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/ALU.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/Decode.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/Execute.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/FSM.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/Fetch.v
  /home/viny/Desktop/interrupt_control/8051-Pipeline/pipelinedV1/pipelinedV1.srcs/sources_1/new/Interrupt_Controler.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/Program_Counter.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/RAM.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/ROM.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/Registers.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/SFR.v
  /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/new/CPU8051.v
}
read_ip -quiet /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/constrs_1/new/micro.xdc
set_property used_in_implementation false [get_files /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/constrs_1/new/micro.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/viny/Desktop/Final_micro_sempipeline/Final_micro_sempipeline.srcs/utils_1/imports/synth_1/CPU8051.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top CPU8051 -part xc7z010clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU8051.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file CPU8051_utilization_synth.rpt -pb CPU8051_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
