#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Apr 06 23:52:20 WEST 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_timer0_func_impl -key {Post-Implementation:sim_1:Functional:tb_timer0} -tclbatch tb_timer0.tcl -view /home/luis/IMP_8051/timer/timer0/tb_timer0_behav.wcfg -log simulate.log"
xsim tb_timer0_func_impl -key {Post-Implementation:sim_1:Functional:tb_timer0} -tclbatch tb_timer0.tcl -view /home/luis/IMP_8051/timer/timer0/tb_timer0_behav.wcfg -log simulate.log

