set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN Y16 [get_ports rst]


set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN U14 [get_ports hsync]
set_property PACKAGE_PIN U15 [get_ports vsync]

set_property PACKAGE_PIN V15 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property PACKAGE_PIN W15 [get_ports {red[1]}]
set_property PACKAGE_PIN T11 [get_ports {red[2]}]
set_property PACKAGE_PIN T10 [get_ports {red[3]}]
set_property PACKAGE_PIN T14 [get_ports {green[0]}]
set_property PACKAGE_PIN T15 [get_ports {green[1]}]
set_property PACKAGE_PIN P14 [get_ports {green[2]}]
set_property PACKAGE_PIN R14 [get_ports {green[3]}]
set_property PACKAGE_PIN W14 [get_ports {blue[0]}]
set_property PACKAGE_PIN Y14 [get_ports {blue[1]}]
set_property PACKAGE_PIN T12 [get_ports {blue[2]}]
set_property PACKAGE_PIN U12 [get_ports {blue[3]}]
