#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue May 27 14:12:28 WEST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ps2bus_time_impl -key {Post-Implementation:sim_1:Timing:ps2bus} -tclbatch ps2bus.tcl -view /home/diana/Downloads/PS2_keyboardbus/PS2_keyboard/ps2bus_behav.wcfg -log simulate.log"
xsim ps2bus_time_impl -key {Post-Implementation:sim_1:Timing:ps2bus} -tclbatch ps2bus.tcl -view /home/diana/Downloads/PS2_keyboardbus/PS2_keyboard/ps2bus_behav.wcfg -log simulate.log

